/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define IRQNO_TIMER2 28
#define IRQNO_I2C1   31

#define LOWEST_PRIORITY  0XF0
#define HIGHEST_PRIORITY 0X00

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t *pNVIC_IserBase = (unit32_t*) 0xE000E100; // Initial address for Interrupt Set-enable Registers
uint32_t *pNVIC_IsprBase = (unit32_t*) 0xE000E200; // Initial address for Interrupt Set-pending Registers
uint32_t *pNVIC_IprBase  = (unit32_t*) 0xE000E400; // Initial address for Interrupt Priority Registers

void configure_priority_for_irqs(uint8_t irq_number, uint8_t priority_value)
{
	// Finds in which IPR are located the target IRQ
	uint8_t irpx = irq_number / 4;
	uint32_t *ipr = pNVIC_IprBase + irpx;

	// Finds the position of IRQ on calculated IRP
	uint8_t irq_position = (irq_number % 4) * 8;

	// Configures the priority
	*ipr &= ~(0xFF << irq_position); // Clears the priority field
	*ipr |= (priority_value << irq_position); // Writes the priority value in priority field
}

int main(void)
{
    printf("Interrupt Priority Exercise\n");

    // Configure the priorities for the peripherals
    configure_priority_for_irqs(IRQNO_TIMER2, 0x80);
    configure_priority_for_irqs(IRQNO_I2C1, 0x80);

	/* Loop forever */
	for(;;);
}

void TIM2_IRQHandler(void)
{
	printf("{TIM2_IRQHandler}\n");
}

void I2C1_EV_IRQHandler(void)
{
	printf("{I2C1_EV_IRQHandler}\n");
}
